
datasets:
    "0": gs://the-peoples-speech-west-europe/peoples-speech-v0.5/train.csv

exporter:
    type: LocalExporter

output_dataset_path: gs://the-peoples-speech-west-europe/peoples-speech-v0.5/train.tar.gz

verbose: True
